version: '3'
services:
  todos-db:
    image: mariadb
    restart: always
    ports:
    - "3501:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: prisma
      MYSQL_PASSWORD: prisma
      MYSQL_DATABASE: todos
    volumes:
      - todos-vol:/var/lib/mysql
volumes:
  todos-vol:
